// <auto-generated />
using System;
using LabRazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabRazorApp.Migrations
{
    [DbContext(typeof(LabContext))]
    [Migration("20251120155100_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LabRazorApp.Models.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrincipalInvestigatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalInvestigatorId");

                    b.ToTable("Experiments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Исследование каталитической активности",
                            PrincipalInvestigatorId = 1,
                            StartDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Катализация A"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Проверка стабильности при 37°C",
                            PrincipalInvestigatorId = 2,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Стабильность B"
                        });
                });

            modelBuilder.Entity("LabRazorApp.Models.Researcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Researchers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivanov@lab.org",
                            FullName = "Иванов И.И.",
                            Position = "PI"
                        },
                        new
                        {
                            Id = 2,
                            Email = "petrov@lab.org",
                            FullName = "Петров П.П.",
                            Position = "Postdoc"
                        });
                });

            modelBuilder.Entity("LabRazorApp.Models.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CollectedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SampleCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("SampleCode")
                        .IsUnique();

                    b.ToTable("Samples");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollectedDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperimentId = 1,
                            SampleCode = "S-2025-0001",
                            Status = "Collected",
                            Type = "tissue"
                        },
                        new
                        {
                            Id = 2,
                            CollectedDate = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExperimentId = 2,
                            SampleCode = "S-2025-0002",
                            Status = "Processed",
                            Type = "solution"
                        });
                });

            modelBuilder.Entity("LabRazorApp.Models.Experiment", b =>
                {
                    b.HasOne("LabRazorApp.Models.Researcher", "PrincipalInvestigator")
                        .WithMany("Experiments")
                        .HasForeignKey("PrincipalInvestigatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrincipalInvestigator");
                });

            modelBuilder.Entity("LabRazorApp.Models.Sample", b =>
                {
                    b.HasOne("LabRazorApp.Models.Experiment", "Experiment")
                        .WithMany("Samples")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("LabRazorApp.Models.Experiment", b =>
                {
                    b.Navigation("Samples");
                });

            modelBuilder.Entity("LabRazorApp.Models.Researcher", b =>
                {
                    b.Navigation("Experiments");
                });
#pragma warning restore 612, 618
        }
    }
}
